// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCm4hOrhD-h7hM3rfE1jIwoGoqKotllBM',
    appId: '1:328204923617:web:555b88350fe13a8535fda0',
    messagingSenderId: '328204923617',
    projectId: 'final-exam-preperation',
    authDomain: 'final-exam-preperation.firebaseapp.com',
    storageBucket: 'final-exam-preperation.firebasestorage.app',
    measurementId: 'G-6P3MSQCH7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAao6zvmfR_m5DRZePfA8magoYQpFW5WOc',
    appId: '1:328204923617:android:8a2974b7932ecedf35fda0',
    messagingSenderId: '328204923617',
    projectId: 'final-exam-preperation',
    storageBucket: 'final-exam-preperation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQIUBtkaDD5hHap3QoCbwgLAelXniFuY',
    appId: '1:328204923617:ios:44d86cad1fa94f2935fda0',
    messagingSenderId: '328204923617',
    projectId: 'final-exam-preperation',
    storageBucket: 'final-exam-preperation.firebasestorage.app',
    iosBundleId: 'com.example.uniForums',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQIUBtkaDD5hHap3QoCbwgLAelXniFuY',
    appId: '1:328204923617:ios:44d86cad1fa94f2935fda0',
    messagingSenderId: '328204923617',
    projectId: 'final-exam-preperation',
    storageBucket: 'final-exam-preperation.firebasestorage.app',
    iosBundleId: 'com.example.uniForums',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCm4hOrhD-h7hM3rfE1jIwoGoqKotllBM',
    appId: '1:328204923617:web:ffe20211c4fbc42435fda0',
    messagingSenderId: '328204923617',
    projectId: 'final-exam-preperation',
    authDomain: 'final-exam-preperation.firebaseapp.com',
    storageBucket: 'final-exam-preperation.firebasestorage.app',
    measurementId: 'G-W7THMVF1HF',
  );
}
